# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: 
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: install hiptest-publisher
  displayName: 'Install hiptest'

- script: hiptest-publisher -c cucumber-js.conf --only=features,step_definitions --test-run-id=427919
  displayName: 'Build tests'

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    node_modules/.bin/cucumber-js --format=json | node_modules/cucumber-junit/bin/cucumber-junit --features-as-suites > junit_output.xml
  displayName: 'Running automated tests'

- script: |
    hiptest-publisher -c cucumber-js.conf --push=junit_output.xml --test-run-id=427919
  displayName: 'Sending results to CucumberStudio'